/**
 * Job titles suggested as people type. Anyone can still type any title they like;
 * these just help with spelling and ideas. Acronyms include the full name so both
 * can be searched ("CEO" or "chief executive").
 */
export const JOB_SUGGESTIONS = [
  "Customer service advisor",
  "Retail sales associate",
  "Cashier",
  "Shop assistant",
  "Store manager",
  "Visual merchandiser",
  "Stock controller",
  "Barista",
  "Waiter / waitress",
  "Bartender",
  "Kitchen porter",
  "Chef",
  "Line cook",
  "Restaurant manager",
  "Hotel receptionist",
  "Hotel housekeeper",
  "Care assistant",
  "Healthcare assistant",
  "Support worker",
  "Nurse",
  "Nursing assistant",
  "Midwife",
  "Paramedic",
  "Pharmacy assistant",
  "Pharmacist",
  "Dental nurse",
  "Receptionist",
  "Medical receptionist",
  "Physiotherapist",
  "Occupational therapist",
  "Social worker",
  "Youth worker",
  "Teaching assistant",
  "Teacher",
  "Nursery practitioner",
  "Childminder",
  "Tutor",
  "Lecturer",
  "School administrator",
  "Warehouse operative",
  "Picker packer",
  "Forklift driver",
  "Delivery driver",
  "Van driver",
  "HGV driver",
  "Courier",
  "Bus driver",
  "Taxi driver",
  "Logistics coordinator",
  "Supply chain analyst",
  "Cleaner",
  "Caretaker",
  "Security officer",
  "Door supervisor",
  "Groundskeeper",
  "Apprentice electrician",
  "Electrician",
  "Plumber",
  "Carpenter",
  "Bricklayer",
  "Painter and decorator",
  "Construction labourer",
  "Site manager",
  "Mechanic",
  "Welder",
  "Maintenance technician",
  "Engineer",
  "Civil engineer",
  "Mechanical engineer",
  "Electrical engineer",
  "Administrative assistant",
  "Office manager",
  "Personal assistant",
  "Data entry clerk",
  "Call centre agent",
  "Customer success manager",
  "Receptionist (office)",
  "HR assistant",
  "HR advisor",
  "Recruiter",
  "Payroll administrator",
  "Accounts assistant",
  "Bookkeeper",
  "Accountant",
  "Financial analyst",
  "Bank teller",
  "Insurance advisor",
  "Sales representative",
  "Business development manager",
  "Account manager",
  "Estate agent",
  "Marketing coordinator",
  "Marketing manager",
  "Social media manager",
  "Content writer",
  "Copywriter",
  "Graphic designer",
  "Product designer",
  "UX designer",
  "Photographer",
  "Video editor",
  "Journalist",
  "Software engineer",
  "Web developer",
  "Front-end developer",
  "Back-end developer",
  "Data analyst",
  "Data scientist",
  "IT support technician",
  "Network engineer",
  "Cyber security analyst",
  "QA tester",
  "Product manager",
  "Project manager",
  "Project coordinator",
  "Business analyst",
  "Operations manager",
  "Team leader",
  "Supervisor",
  "Shift manager",
  "Charity fundraiser",
  "Volunteer coordinator",
  "Community outreach worker",
  "Paralegal",
  "Solicitor",
  "Legal secretary",
  "Police officer",
  "Firefighter",
  "Prison officer",
  "Civil servant",
  "Council officer",
  "Armed forces",
  "Hairdresser",
  "Barber",
  "Beauty therapist",
  "Nail technician",
  "Fitness instructor",
  "Personal trainer",
  "Lifeguard",
  "Event staff",
  "Event coordinator",
  "Travel agent",
  "Flight attendant",
  "Airport operative",
  "Gardener",
  "Farm worker",
  "Veterinary nurse",
  "Dog groomer",
  "Lab technician",
  "Research assistant",
  "Scientist",
  "Interpreter",
  "Translator",
  "Apprentice",
  "Graduate trainee",
  "Intern",
  "CEO (chief executive officer)",
  "Founder",
  "Co-founder",
  "Managing director",
  "COO (chief operating officer)",
  "CFO (chief financial officer)",
  "CTO (chief technology officer)",
  "CMO (chief marketing officer)",
  "Chief of staff",
  "General manager",
  "Head of department",
  "Director",
  "Non-executive director",
  "Board member",
  "Entrepreneur",
  "Small business owner",
  "Franchise owner",
  "Creative writer",
  "Content creator",
  "YouTuber",
  "Influencer",
  "Podcast producer",
  "Podcast host",
  "Streamer",
  "Blogger",
  "Author",
  "Editor",
  "Sub-editor",
  "Proofreader",
  "Scriptwriter",
  "Screenwriter",
  "Poet",
  "Ghostwriter",
  "Technical writer",
  "Grant writer",
  "Communications officer",
  "PR assistant",
  "Public relations manager",
  "Press officer",
  "Brand manager",
  "Brand ambassador",
  "Community manager",
  "SEO specialist",
  "Digital marketing executive",
  "Email marketing specialist",
  "Growth marketer",
  "Performance marketing manager",
  "Influencer marketing manager",
  "Creative director",
  "Art director",
  "Illustrator",
  "Animator",
  "Motion designer",
  "3D artist",
  "Concept artist",
  "Game designer",
  "Game developer",
  "Level designer",
  "Game tester",
  "Fashion designer",
  "Fashion buyer",
  "Stylist",
  "Makeup artist",
  "Interior designer",
  "Architect",
  "Architectural technician",
  "Landscape architect",
  "Musician",
  "Music producer",
  "Sound engineer",
  "DJ",
  "Music teacher",
  "Actor",
  "Dancer",
  "Theatre technician",
  "Stage manager",
  "Camera operator",
  "Film producer",
  "Film director",
  "Production assistant",
  "Runner (TV and film)",
  "Radio presenter",
  "TV presenter",
  "Museum assistant",
  "Gallery assistant",
  "Librarian",
  "Archivist",
  "Curator",
  "Tattoo artist",
  "Florist",
  "Baker",
  "Pastry chef",
  "Butcher",
  "Fishmonger",
  "Sous chef",
  "Head chef",
  "Catering assistant",
  "School cook",
  "Food delivery rider",
  "Fast food crew member",
  "Host / hostess",
  "Sommelier",
  "Hotel manager",
  "Concierge",
  "Night porter",
  "Tour guide",
  "Holiday rep",
  "Cabin crew",
  "Pilot",
  "Air traffic controller",
  "Train driver",
  "Train conductor",
  "Station assistant",
  "Ship crew",
  "Postal worker",
  "Refuse collector",
  "Street cleaner",
  "Recycling operative",
  "Window cleaner",
  "Handyperson",
  "Roofer",
  "Plasterer",
  "Tiler",
  "Glazier",
  "Scaffolder",
  "Gas engineer",
  "Heating engineer",
  "Solar panel installer",
  "Wind turbine technician",
  "Electric vehicle technician",
  "Car valeter",
  "Vehicle technician",
  "Tyre fitter",
  "MOT tester",
  "Car sales executive",
  "Machine operator",
  "Production operative",
  "Factory worker",
  "Quality inspector",
  "Quality assurance manager",
  "Assembly worker",
  "CNC machinist",
  "Toolmaker",
  "Fabricator",
  "Joiner",
  "Upholsterer",
  "Locksmith",
  "Surveyor",
  "Quantity surveyor",
  "Health and safety officer",
  "Environmental officer",
  "Ecologist",
  "Conservation worker",
  "Park ranger",
  "Tree surgeon",
  "Horticulturist",
  "Zookeeper",
  "Animal care assistant",
  "Dog walker",
  "Veterinarian",
  "Farrier",
  "Doctor",
  "GP (general practitioner)",
  "Junior doctor",
  "Surgeon",
  "Psychiatrist",
  "Psychologist",
  "Counsellor",
  "Therapist",
  "Mental health nurse",
  "Mental health support worker",
  "Speech and language therapist",
  "Dietitian",
  "Nutritionist",
  "Optician",
  "Optometrist",
  "Radiographer",
  "Sonographer",
  "Phlebotomist",
  "Hospital porter",
  "Ward clerk",
  "Care home manager",
  "Home carer",
  "Personal care assistant",
  "Occupational health advisor",
  "Dentist",
  "Dental hygienist",
  "Dental receptionist",
  "Pharmacy technician",
  "Chiropractor",
  "Massage therapist",
  "Yoga teacher",
  "Sports coach",
  "Football coach",
  "Swimming teacher",
  "Leisure centre assistant",
  "Gym receptionist",
  "Headteacher",
  "Deputy headteacher",
  "Special educational needs teacher",
  "SENCO",
  "Learning support assistant",
  "Early years educator",
  "Primary school teacher",
  "Secondary school teacher",
  "Teaching assistant apprentice",
  "Exam invigilator",
  "School counsellor",
  "Careers advisor",
  "Academic researcher",
  "PhD student",
  "Student ambassador",
  "University administrator",
  "Admissions officer",
  "Training coordinator",
  "Learning and development manager",
  "HR manager",
  "HR business partner",
  "Talent acquisition specialist",
  "Office administrator",
  "Receptionist and administrator",
  "Executive assistant",
  "Virtual assistant",
  "Secretary",
  "Medical secretary",
  "Court clerk",
  "Barrister",
  "Legal assistant",
  "Conveyancer",
  "Compliance officer",
  "Risk analyst",
  "Auditor",
  "Tax advisor",
  "Investment analyst",
  "Financial advisor",
  "Mortgage advisor",
  "Credit controller",
  "Debt advisor",
  "Claims handler",
  "Underwriter",
  "Actuary",
  "Economist",
  "Statistician",
  "Procurement officer",
  "Buyer",
  "Merchandiser",
  "E-commerce assistant",
  "Online seller",
  "Customer support specialist",
  "Technical support engineer",
  "Help desk analyst",
  "Complaints handler",
  "Telesales agent",
  "Field sales representative",
  "Sales manager",
  "Key account manager",
  "Retail supervisor",
  "Assistant store manager",
  "Area manager",
  "Department manager",
  "Store detective",
  "Loss prevention officer",
  "Stock assistant",
  "Night shift stock replenisher",
  "Delivery supervisor",
  "Warehouse supervisor",
  "Warehouse manager",
  "Transport planner",
  "Fleet manager",
  "Freight forwarder",
  "Customs officer",
  "Border force officer",
  "Immigration officer",
  "Probation officer",
  "Police community support officer",
  "Special constable",
  "Paramedic apprentice",
  "Emergency call handler",
  "Coastguard",
  "Soldier",
  "Royal Navy sailor",
  "RAF engineer",
  "Army officer",
  "Politician",
  "Parliamentary researcher",
  "Policy advisor",
  "Local government officer",
  "Housing officer",
  "Benefits advisor",
  "Job coach",
  "Employment advisor",
  "Charity worker",
  "Charity shop volunteer",
  "Community organiser",
  "Campaigner",
  "Fundraising manager",
  "Faith leader",
  "Foster carer",
  "Nanny",
  "Au pair",
  "Babysitter",
  "Playworker",
  "Camp counsellor",
  "Sports referee",
  "Esports player",
  "Personal shopper",
  "Estate manager",
  "Property manager",
  "Lettings agent",
  "Building manager",
  "Facilities manager",
  "Maintenance supervisor",
  "Cleaning supervisor",
  "Laundry assistant",
  "Dry cleaner",
  "Tailor",
  "Seamstress",
  "Jeweller",
  "Watch repairer",
  "Phone repair technician",
  "Computer technician",
  "IT manager",
  "Systems administrator",
  "DevOps engineer",
  "Cloud engineer",
  "Site reliability engineer",
  "Machine learning engineer",
  "AI engineer",
  "Prompt engineer",
  "Full-stack developer",
  "Mobile app developer",
  "iOS developer",
  "Android developer",
  "Game programmer",
  "Embedded systems engineer",
  "Database administrator",
  "Data engineer",
  "BI analyst",
  "Solutions architect",
  "Technical lead",
  "Engineering manager",
  "Scrum master",
  "Agile coach",
  "Product owner",
  "UX researcher",
  "UI designer",
  "Web designer",
  "Digital designer",
  "Penetration tester",
  "Security engineer",
  "Blockchain developer",
  "Hardware engineer",
  "Robotics engineer",
  "Aerospace engineer",
  "Chemical engineer",
  "Biomedical engineer",
  "Structural engineer",
  "Automotive engineer",
  "Energy engineer",
  "Environmental engineer",
  "Manufacturing engineer",
  "Process engineer",
  "Chemist",
  "Biologist",
  "Physicist",
  "Geologist",
  "Pharmacologist",
  "Clinical research associate",
  "Lab assistant",
  "Forensic scientist",
  "Meteorologist",
  "Astronomer",
];
